version: "3.9"

services:
  web:
    image: codeceptjs-visual-testing:local
    ports:
      - "3000:3000"
    command: "npm run test:server"
  tests:
    image: codeceptjs-visual-testing:local
    depends_on:
      - web
    command: "npm run test"