name: Test

on: push

jobs:
  e2e-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Images
      run: docker build . -t codeceptjs-visual-testing:local

    - name: Run Tests
      run: docker compose run tests
