name: Test
on: push
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Containers
        run: docker compose -f "./tests/docker-compose.yml" build

      - name: Test
        run: docker compose -f "./tests/docker-compose.yml" run codeceptjs; echo $?
